-- AlterTable
ALTER TABLE "Authentication" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Booker" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Contact" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
